-- Clangd Language Server Configuration (C/C++)
-- Repository: https://github.com/clangd/clangd
-- Documentation: https://clangd.llvm.org/
--
-- This LSP provides:
-- - C and C++ language support (C++17/20/23)
-- - Code completion
-- - Go to definition, find references
-- - Code navigation and refactoring
-- - Clang-tidy integration
-- - Header file management
--
-- Requirements:
-- - clangd binary installed (via LLVM, brew install llvm, or Mason)
-- - compile_commands.json in project root (generated by CMake, Bear, etc.)
--
-- Supported filetypes: c, cpp, objc, objcpp, cuda, proto

return {
	-- Default configuration (works well out of the box)
	-- Mason will install clangd automatically if not found

	-- Uncomment and customize if needed:
	-- cmd = {
	--     'clangd',
	--     '--background-index',           -- Index project in background
	--     '--clang-tidy',                 -- Enable clang-tidy diagnostics
	--     '--completion-style=detailed',  -- Detailed completion info
	--     '--header-insertion=iwyu',      -- Insert headers (include-what-you-use)
	--     '--pch-storage=memory',         -- Store precompiled headers in memory
	-- },

	-- filetypes = { 'c', 'cpp', 'objc', 'objcpp', 'cuda', 'proto' },

	-- Custom capabilities (optional)
	-- capabilities = {
	--     offsetEncoding = { 'utf-16' },  -- Use UTF-16 encoding
	-- },

	-- Server-specific settings (optional)
	-- init_options = {
	--     clangdFileStatus = true,
	--     usePlaceholders = true,
	--     completeUnimported = true,
	--     semanticHighlighting = true,
	-- },
}
